#
# create empty scene
#
/vis/scene/create
#
# Create a scene handler for a specific graphics system
# (Edit the next line(s) to choose another graphic system)
#
/vis/open OGLIXm
#
#/vis/open DAWNFILE
#
# draw scene
#
/vis/viewer/set/viewpointThetaPhi 45 45 deg
/vis/viewer/zoom 1.0
/vis/viewer/flush
#
# for drawing the tracks
# (if too many tracks cause core dump => storeTrajectory 0)
/tracking/storeTrajectory 1
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate

